hostNetwork: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

tolerations:
  - operator: Exists

securityContext:
  runAsNonRoot: true
  readOnlyRootFilesystem: true
