apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-a-quota
  namespace: team-a

spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi

    limits.cpu: "40"
    limits.memory: 80Gi

    pods: "100"
