apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-storage

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: premium-storage

  resources:
    requests:
      storage: 50Gi
